/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeeklyPlanRouteImport } from './routes/_app.weekly-plan'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMealPlanRouteImport } from './routes/_app.meal-plan'
import { Route as AppMacroHistoryRouteImport } from './routes/_app.macro-history'
import { Route as AppMacroCalculatorRouteImport } from './routes/_app.macro-calculator'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyPlanRoute = AppWeeklyPlanRouteImport.update({
  id: '/weekly-plan',
  path: '/weekly-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMealPlanRoute = AppMealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppMacroHistoryRoute = AppMacroHistoryRouteImport.update({
  id: '/macro-history',
  path: '/macro-history',
  getParentRoute: () => AppRoute,
} as any)
const AppMacroCalculatorRoute = AppMacroCalculatorRouteImport.update({
  id: '/macro-calculator',
  path: '/macro-calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/macro-calculator': typeof AppMacroCalculatorRoute
  '/macro-history': typeof AppMacroHistoryRoute
  '/meal-plan': typeof AppMealPlanRoute
  '/profile': typeof AppProfileRoute
  '/weekly-plan': typeof AppWeeklyPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/macro-calculator': typeof AppMacroCalculatorRoute
  '/macro-history': typeof AppMacroHistoryRoute
  '/meal-plan': typeof AppMealPlanRoute
  '/profile': typeof AppProfileRoute
  '/weekly-plan': typeof AppWeeklyPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/macro-calculator': typeof AppMacroCalculatorRoute
  '/_app/macro-history': typeof AppMacroHistoryRoute
  '/_app/meal-plan': typeof AppMealPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/weekly-plan': typeof AppWeeklyPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/macro-calculator'
    | '/macro-history'
    | '/meal-plan'
    | '/profile'
    | '/weekly-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/macro-calculator'
    | '/macro-history'
    | '/meal-plan'
    | '/profile'
    | '/weekly-plan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/macro-calculator'
    | '/_app/macro-history'
    | '/_app/meal-plan'
    | '/_app/profile'
    | '/_app/weekly-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-plan': {
      id: '/_app/weekly-plan'
      path: '/weekly-plan'
      fullPath: '/weekly-plan'
      preLoaderRoute: typeof AppWeeklyPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal-plan': {
      id: '/_app/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof AppMealPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/macro-history': {
      id: '/_app/macro-history'
      path: '/macro-history'
      fullPath: '/macro-history'
      preLoaderRoute: typeof AppMacroHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/macro-calculator': {
      id: '/_app/macro-calculator'
      path: '/macro-calculator'
      fullPath: '/macro-calculator'
      preLoaderRoute: typeof AppMacroCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMacroCalculatorRoute: typeof AppMacroCalculatorRoute
  AppMacroHistoryRoute: typeof AppMacroHistoryRoute
  AppMealPlanRoute: typeof AppMealPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWeeklyPlanRoute: typeof AppWeeklyPlanRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMacroCalculatorRoute: AppMacroCalculatorRoute,
  AppMacroHistoryRoute: AppMacroHistoryRoute,
  AppMealPlanRoute: AppMealPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppWeeklyPlanRoute: AppWeeklyPlanRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
